# Generated by Django 4.2.16 on 2024-11-12 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0002_rename_result_voter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='voter',
            new_name='Voters',
        ),
    ]
