# Generated by Django 4.2.16 on 2024-11-12 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0003_rename_voter_voters'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Voters',
            new_name='Voter',
        ),
    ]
