# Generated by Django 4.2.16 on 2024-11-12 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0004_rename_voters_voter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Voter',
        ),
    ]
