# Generated by Django 4.2.16 on 2024-10-17 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image_url',
        ),
    ]
