# Generated by Django 4.2.16 on 2024-11-22 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tactoss', '0002_alter_friend_profile2_alter_friend_user1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='profile2',
            new_name='user2',
        ),
    ]
