# Generated by Django 4.2.16 on 2024-11-22 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tactoss', '0003_rename_profile2_friend_user2'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmokeGif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gif', models.ImageField(upload_to='')),
                ('map', models.TextField()),
                ('area', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tactoss.user')),
            ],
        ),
    ]
