# Generated by Django 4.2.16 on 2024-11-23 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tactoss', '0005_remove_friend_user1_remove_friend_user2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='join_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='smokegif',
            name='published',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
