# Generated by Django 4.2.16 on 2024-11-24 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tactoss', '0006_account_join_date_smokegif_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smokegif',
            name='published',
            field=models.DateField(auto_now=True),
        ),
    ]
