# Generated by Django 4.2.16 on 2024-11-24 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tactoss', '0007_alter_smokegif_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='join_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='smokegif',
            name='published',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
