# Generated by Django 4.2.16 on 2024-12-08 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tactoss', '0009_account_is_in_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tactoss.team'),
        ),
    ]
