# Generated by Django 4.2.16 on 2024-12-09 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tactoss', '0010_account_user_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_in_team',
        ),
        migrations.AddField(
            model_name='account',
            name='friends',
            field=models.ManyToManyField(blank=True, to='tactoss.account'),
        ),
    ]
