# Generated by Django 4.2.16 on 2024-12-09 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tactoss', '0011_remove_account_is_in_team_account_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend_Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_account', to='tactoss.account')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_account', to='tactoss.account')),
            ],
        ),
    ]
