# Generated by Django 4.2.16 on 2024-12-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tactoss', '0012_friend_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='elo_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
