# Generated by Django 4.2.16 on 2024-10-10 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0002_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Status',
            new_name='StatusMessage',
        ),
    ]
